### ISSUE TITLE
Crash in plot script: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#381] opened 2017-03-30 17:05 UTC
```
wilfred:warmup_experiment> ./bin/plot_krun_results annotated_results/warmup_results_0_8_linux2_i7_4790_outliers_w200_changepoints.json.bz2 -b bencher5:richards:C:default-c:0 -o /tmp/a.pdf --cycles 1,2                        
Saving results to: /tmp/a.pdf
Using matplotlib version 1.5.3 with backend agg
Charting with sliding window size: 200, xlimits: None
Loading: annotated_results/warmup_results_0_8_linux2_i7_4790_outliers_w200_changepoints.json.bz2
No VM instrumentation data is available.
Adding run sequence to  richards:C:default-c bencher5
Plotting Linux$_\mathrm{4790}$: Richards (C) on page 01 of 01.
1 plots arranged in 1 rows and 1 columns.
Saved: /tmp/a.pdf
Traceback (most recent call last):
  File "./bin/plot_krun_results", line 1564, in <module>
    inset_xlimits=options.inset_xlimits)
  File "./bin/plot_krun_results", line 316, in main
    core_cycles, cycles_ylimits, inset_xlimits)
  File "./bin/plot_krun_results", line 930, in draw_page
    tukey, core_cycles, cycles_ylimits, inset_x_bounds))
  File "./bin/plot_krun_results", line 415, in __init__
    for core in self.core_cycles:  # For each core specified on command line.
TypeError: 'NoneType' object is not iterable
```

Note that `--cycles` is not a valid argument. This does not happen if you replace `--cycles` with `--core-cycles`. Is the argument being interpreted as `--cycles-ylimits` perhaps?

**Comment by snim2** [comment] 2017-03-30 17:06
Possibly, I'm not sure how `argparse` deals with things like that.

**Comment by snim2** [comment] 2017-03-31 10:44
OK, I have had a quick look at this, the problem is that you are taking in a string and splitting the string into ints (similarly with `--cycles-ylimits`). The argparse way of doing things is to allow the parser to split the list and check the types, in which case the script would have to be called like this:

```sh
./bin/plot_krun_results --core-cycles 1 2 -o silly.pdf  warmup_results_0_7_linux1_i7_4790k.json.bz2
```

Note, if you put `--core-cycles` after `-o` then argparse will be confused between the optional number of arguments to `--core-cycles` and the positional argument `warmup_results_0_7...`. 

Do you want me to push a fix for this or leave it for now?

**Comment by vext01** [comment] 2017-03-31 10:55
It's not super critical. I think our time is better spent elsewhere for now.

**Comment by snim2** [comment] 2017-03-31 10:57
OK, I have pushed a branch `fix-381`, we can get to testing it later.

**Comment by snim2** [comment] 2018-02-10 19:28
This bug was originally a user-error, and is low priority, so closing. If we wanted to re-open, the fix would be to change some CLI options to make them less confusing.

**Closed as completed by snim2** 2018-02-10 19:28 UTC
Labels: bug
