### ISSUE TITLE
--no-inset changes zoom plot

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#405] opened 2017-05-22 14:02 UTC
```
${PLOT_DIR}/warmup00a.pdf:
	${EXPERIMENT_REPO}/bin/plot_krun_results --export-size ${SLIDE_WIDTH},${SLIDE_HEIGHT} -o $@ -b bencher6:fannkuch_redux:LuaJIT:default-lua:11 --no-inset --wallclock-only ${BENCHER6_DATA}

${PLOT_DIR}/warmup00b.pdf:
	${EXPERIMENT_REPO}/bin/plot_krun_results --export-size ${SLIDE_WIDTH},${SLIDE_HEIGHT} -o $@ -b bencher6:fannkuch_redux:LuaJIT:default-lua:11 --wallclock-only --with-outliers ${BENCHER6_DATA}
```

![ug](https://cloud.githubusercontent.com/assets/604955/26312456/8a79d5e0-3eff-11e7-901e-dd1f6cdb2c04.png)

**Comment by snim2** [comment] 2017-05-22 15:00
I can't reproduce this with matplotlib 2.0.0:

```sh
$ ../bin/plot_krun_results -o test_n^Cset.pdf -b bencher6:fannkuch_redux:LuaJIT:default-lua:11  --no-inset --wallclock-only bencher6/warmup_results_outliers_w200changepoints.json.bz2 
../bin/plot_krun_results -o test_with_inset.pdf -b bencher6:fannkuch_redux:LuaJIT:default-lua:11 --wallclock-only bencher6/warmup_results_outliers_w200_changpoints.json.bz2 
```

gives my y-limits of `0.56525 ... 0.56631` on the zoom chart.

**Comment by vext01** [comment] 2017-05-22 15:34
Im using py-matplotlib-1.5.3p2

Could be a matplotlib bug then...

**Comment by snim2** [comment] 2017-05-22 15:35
Bencher 2 has the latest matplotlib installed, I think this is not the first "bug" that has been fixed by moving to the later version. So, I'll close this now, you can re-open if you find it can be triggered on v2.0, but hopefully that won't be necessary.

**Closed as completed by snim2** 2017-05-22 15:35 UTC
